services:
  mongo:
    image: mongo:8.0.6
    container_name: ${MONGO_CONTAINER_NAME:-mongodb}
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD:-password}
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    # 確保容器能被發現
    networks:
      - default
  
  mongo-express:
    image: mongo-express:latest
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME:-mongo-express}
    restart: always
    ports:
      - "${MONGO_EXPRESS_PORT:-8081}:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_ROOT_USERNAME:-root}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - ME_CONFIG_MONGODB_SERVER=${MONGO_CONTAINER_NAME:-mongo}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
      - ME_CONFIG_MONGODB_URL=mongodb://${MONGO_ROOT_USERNAME:-root}:${MONGO_ROOT_PASSWORD:-password}@${MONGO_CONTAINER_NAME:-mongo}:27017/admin
      # 添加基本認證
      # - ME_CONFIG_BASICAUTH_USERNAME=${MONGO_EXPRESS_BASICAUTH_USERNAME:-admin}
      # - ME_CONFIG_BASICAUTH_PASSWORD=${MONGO_EXPRESS_BASICAUTH_PASSWORD:-pass}
      # 明確禁用基本認證
      - ME_CONFIG_BASICAUTH=${MONGO_EXPRESS_BASICAUTH:-false}
    depends_on:
      - mongo
    networks:
      - default

volumes:
  mongo-data:
    driver: local
  mongo-config:
    driver: local

networks:
  default:
    external: true
    name: ${NETWORK_NAME:-nginx-proxy}